name: vae_pancancer
channels:
- conda-forge
- defaults
dependencies:
- keras=2.0.6
- tensorflow=1.0.1
- hdf5=1.8.17
- scikit-learn=0.18.1
- statsmodels=0.8.0
- jupyter=1.0.0
- ipython=4.1.2
- pandas=0.20.3
- numpy=1.12.1
- matplotlib=2.0.0
- seaborn=0.7.1
- numexpr=2.6.2
- pydot=1.0.28
- graphviz=2.38.0
- python-graphviz=0.5.2
- subprocess32
